version: "3.9"
services:
  java-maven-app:
    image: miltosdev/my-private-repo:5.0.11-build-19
    ports:
      - "8080:8080"
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
